package com.fuzify.isms.hb;
// Generated Jun 24, 2009 4:49:04 PM by Hibernate Tools 3.1.0.beta5


import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;
/**
 * Captcha generated by hbm2java
 */
@XmlRootElement
public class Captcha  implements java.io.Serializable {

    // Fields    

     private int captchaId;
     private String name;
     private String imageUrl;
     private String configUrl;
     private Set membermessages = new HashSet(0);

     // Constructors

    /** default constructor */
    public Captcha() {
    }

    /** full constructor */
    public Captcha(String name, String imageUrl, String configUrl, Set membermessages) {
       this.name = name;
       this.imageUrl = imageUrl;
       this.configUrl = configUrl;
       this.membermessages = membermessages;
    }
    
   
    // Property accessors
    public int getCaptchaId() {
        return this.captchaId;
    }
    
    public void setCaptchaId(int captchaId) {
        this.captchaId = captchaId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public String getConfigUrl() {
        return this.configUrl;
    }
    
    public void setConfigUrl(String configUrl) {
        this.configUrl = configUrl;
    }
    public Set getMembermessages() {
        return this.membermessages;
    }
    
    public void setMembermessages(Set membermessages) {
        this.membermessages = membermessages;
    }




}


