package com.fuzify.isms.hb;
// Generated Jun 24, 2009 4:49:04 PM by Hibernate Tools 3.1.0.beta5


import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;
/**
 * MemberStatus generated by hbm2java
 */
@XmlRootElement
public class MemberStatus  implements java.io.Serializable {

    // Fields    

     private int statusId;
     private String status;
     private Set members = new HashSet(0);

     // Constructors

    /** default constructor */
    public MemberStatus() {
    }

	/** minimal constructor */
    public MemberStatus(String status) {
        this.status = status;
    }
    /** full constructor */
    public MemberStatus(String status, Set members) {
       this.status = status;
       this.members = members;
    }
    
   
    // Property accessors
    public int getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getMembers() {
        return this.members;
    }
    
    public void setMembers(Set members) {
        this.members = members;
    }




}


