package com.fuzify.isms.hb;
// Generated Jun 24, 2009 4:49:04 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;
/**
 * MemberMessage generated by hbm2java
 */
@XmlRootElement
public class MemberMessage  implements java.io.Serializable {

    // Fields    

     private int memberMessageId;
     private Captcha captcha;
     private MessageStatus messagestatus;
     private int mobile;
     private String message;
     private int messageId;
     private Date created;

     // Constructors

    /** default constructor */
    public MemberMessage() {
    }

	/** minimal constructor */
    public MemberMessage(int mobile, String message) {
        this.mobile = mobile;
        this.message = message;
    }
    /** full constructor */
    public MemberMessage(Captcha captcha, MessageStatus messagestatus, int mobile, String message, int messageId, Date created) {
       this.captcha = captcha;
       this.messagestatus = messagestatus;
       this.mobile = mobile;
       this.message = message;
       this.messageId = messageId;
       this.created = created;
    }
    
   
    // Property accessors
    public int getMemberMessageId() {
        return this.memberMessageId;
    }
    
    public void setMemberMessageId(int memberMessageId) {
        this.memberMessageId = memberMessageId;
    }
    public Captcha getCaptcha() {
        return this.captcha;
    }
    
    public void setCaptcha(Captcha captcha) {
        this.captcha = captcha;
    }
    public MessageStatus getMessagestatus() {
        return this.messagestatus;
    }
    
    public void setMessagestatus(MessageStatus messagestatus) {
        this.messagestatus = messagestatus;
    }
    public int getMobile() {
        return this.mobile;
    }
    
    public void setMobile(int mobile) {
        this.mobile = mobile;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public int getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(int messageId) {
        this.messageId = messageId;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


