package com.fuzify.isms.hb;
// Generated Jun 24, 2009 4:49:04 PM by Hibernate Tools 3.1.0.beta5



import javax.xml.bind.annotation.XmlRootElement;
/**
 * MemberContact generated by hbm2java
 */
@XmlRootElement
public class MemberContact  implements java.io.Serializable {

    // Fields    

     private int memberContactId;
     private Member member;
     private String email;
     private int mobile;
     private String firstname;
     private String lastname;

     // Constructors

    /** default constructor */
    public MemberContact() {
    }

	/** minimal constructor */
    public MemberContact(Member member, int mobile) {
        this.member = member;
        this.mobile = mobile;
    }
    /** full constructor */
    public MemberContact(Member member, String email, int mobile, String firstname, String lastname) {
       this.member = member;
       this.email = email;
       this.mobile = mobile;
       this.firstname = firstname;
       this.lastname = lastname;
    }
    
   
    // Property accessors
    public int getMemberContactId() {
        return this.memberContactId;
    }
    
    public void setMemberContactId(int memberContactId) {
        this.memberContactId = memberContactId;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getMobile() {
        return this.mobile;
    }
    
    public void setMobile(int mobile) {
        this.mobile = mobile;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }




}


