package com.fuzify.isms.hb;
// Generated Jun 24, 2009 4:49:04 PM by Hibernate Tools 3.1.0.beta5


import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;
/**
 * MessageStatus generated by hbm2java
 */
@XmlRootElement
public class MessageStatus  implements java.io.Serializable {

    // Fields    

     private int id;
     private int messageStatusId;
     private String status;
     private Set membermessages = new HashSet(0);

     // Constructors

    /** default constructor */
    public MessageStatus() {
    }

    /** full constructor */
    public MessageStatus(int messageStatusId, String status, Set membermessages) {
       this.messageStatusId = messageStatusId;
       this.status = status;
       this.membermessages = membermessages;
    }
    
   
    // Property accessors
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getMessageStatusId() {
        return this.messageStatusId;
    }
    
    public void setMessageStatusId(int messageStatusId) {
        this.messageStatusId = messageStatusId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getMembermessages() {
        return this.membermessages;
    }
    
    public void setMembermessages(Set membermessages) {
        this.membermessages = membermessages;
    }




}


