package com.fuzify.isms.hb;
// Generated Jun 24, 2009 4:49:04 PM by Hibernate Tools 3.1.0.beta5



import javax.xml.bind.annotation.XmlRootElement;
/**
 * OrkutMember generated by hbm2java
 */
@XmlRootElement
public class OrkutMember  implements java.io.Serializable {

    // Fields    

     private Long orkutMemberId;
     private Long memberId;
     private Long orkutId;

     // Constructors

    /** default constructor */
    public OrkutMember() {
    }

    /** full constructor */
    public OrkutMember(Long memberId, Long orkutId) {
       this.memberId = memberId;
       this.orkutId = orkutId;
    }
    
   
    // Property accessors
    public Long getOrkutMemberId() {
        return this.orkutMemberId;
    }
    
    public void setOrkutMemberId(Long orkutMemberId) {
        this.orkutMemberId = orkutMemberId;
    }
    public Long getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }
    public Long getOrkutId() {
        return this.orkutId;
    }
    
    public void setOrkutId(Long orkutId) {
        this.orkutId = orkutId;
    }




}


